# Project: VariableRange
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = src/main.o src/func.o src/static.o
LINKOBJ  = src/main.o src/func.o src/static.o
LIBS     = -L"D:/Weekend/hhs/tools/Dev-Cpp/MinGW64/lib" -L"D:/Weekend/hhs/tools/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Weekend/hhs/tools/Dev-Cpp/MinGW64/include" -I"D:/Weekend/hhs/tools/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Weekend/hhs/tools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Weekend/hhs/tools/Dev-Cpp/MinGW64/include" -I"D:/Weekend/hhs/tools/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Weekend/hhs/tools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Weekend/hhs/tools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = VariableRange.exe
CXXFLAGS = $(CXXINCS) -ansi -traditional-cpp
CFLAGS   = $(INCS) -ansi -traditional-cpp
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

src/main.o: src/main.c
	$(CC) -c src/main.c -o src/main.o $(CFLAGS)

src/func.o: src/func.c
	$(CC) -c src/func.c -o src/func.o $(CFLAGS)

src/static.o: src/static.c
	$(CC) -c src/static.c -o src/static.o $(CFLAGS)
